version: "3"

services:
  study-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: study
      POSTGRES_USER: study
      POSTGRES_DB: study
#  member-be:
#    image: study-member-be
#    ports:
#      - 28081:18081
#    depends_on:
#      - member-db
#    links:
#      - member-db